from typing import Any

JD_ANTI_PATTERNS: list[str] = [
    "chatgpt",
    "prompt engineering",
    "langchain tutorial",
    "content creation",
    "marketing manager",
]

CONSULTING_COMPANIES: set[str] = {
    "tcs",
    "infosys",
    "wipro",
    "accenture",
    "cognizant",
    "capgemini",
    "hcl",
    "tech mahindra",
    "l&t infotech",
    "mindtree",
    "ltimindtree",
    "mphasis",
    "hexaware",
    "cyient",
    "persistent",
}

CONSULTING_WITH_ML_BOOKS: set[str] = {
    "accenture",
    "ibm",
    "cognizant",
    "tcs",
    "infosys",
}

SENIORITY_KEYWORDS: list[str] = [
    "senior",
    "staff",
    "principal",
    "lead",
    "head",
    "chief",
    "manager",
    "director",
    "architect",
    "fellow",
]

COMPANY_TIERS: dict[str, dict[str, Any]] = {
    "tier1": {
        "companies": {
            "google",
            "meta",
            "microsoft",
            "amazon",
            "apple",
            "netflix",
            "openai",
            "deepmind",
            "anthropic",
            "nvidia",
            "ibm research",
            "microsoft research",
        },
        "score": 1.0,
    },
    "tier2": {
        "companies": {
            "uber",
            "lyft",
            "airbnb",
            "twitter",
            "linkedin",
            "salesforce",
            "oracle",
            "adobe",
            "intel",
            "ibm",
            "databricks",
            "snowflake",
            "palantir",
            "stripe",
            "square",
            "shopify",
            "spotify",
            "slack",
            "mongodb",
            "elastic",
        },
        "score": 0.85,
    },
    "tier3": {
        "companies": {
            "flipkart",
            "ola",
            "paytm",
            "swiggy",
            "zomato",
            "razorpay",
            "phonepe",
            "cred",
            "freshworks",
            "chargebee",
            "postman",
            "hasura",
            "zoho",
            "dream11",
            "unacademy",
            "byju",
            "meesho",
            "sharechat",
            "dunzo",
            "groww",
            "upstox",
        },
        "score": 0.70,
    },
    "tier4": {
        "companies": {
            "tcs",
            "infosys",
            "wipro",
            "hcl",
            "tech mahindra",
            "ltimindtree",
            "mindtree",
            "mphasis",
            "hexaware",
        },
        "score": 0.50,
    },
}

SKILL_CATEGORIES: dict[str, set[str]] = {
    "cloud_infra": {
        "aws",
        "gcp",
        "azure",
        "docker",
        "kubernetes",
        "terraform",
        "cloudformation",
        "jenkins",
        "ci/cd",
        "ansible",
        "puppet",
        "chef",
        "helm",
        "istio",
    },
    "ml_ai": {
        "machine learning",
        "deep learning",
        "nlp",
        "computer vision",
        "tensorflow",
        "pytorch",
        "keras",
        "scikit-learn",
        "xgboost",
        "lightgbm",
        "catboost",
        "hugging face",
        "transformers",
        "neural network",
        "llm",
        "rag",
        "langchain",
        "lora",
        "qlora",
        "peft",
        "mlops",
        "model deployment",
        "model serving",
    },
    "data_engineering": {
        "spark",
        "kafka",
        "airflow",
        "hadoop",
        "hive",
        "presto",
        "trino",
        "dbt",
        "looker",
        "tableau",
        "power bi",
        "etl",
        "data pipeline",
        "data warehouse",
        "snowflake",
        "redshift",
        "bigquery",
        "databricks",
    },
    "backend": {
        "python",
        "java",
        "scala",
        "go",
        "rust",
        "c++",
        "node.js",
        "typescript",
        "django",
        "flask",
        "fastapi",
        "spring boot",
        "microservices",
        "rest api",
        "graphql",
        "grpc",
    },
    "databases": {
        "sql",
        "mysql",
        "postgresql",
        "mongodb",
        "cassandra",
        "redis",
        "elasticsearch",
        "dynamodb",
        "cosmosdb",
        "couchbase",
    },
    "vector_search": {
        "faiss",
        "pinecone",
        "weaviate",
        "qdrant",
        "milvus",
        "annoy",
        "hnsw",
        "vector search",
        "embedding",
        "sentence-transformer",
        "dense retrieval",
        "sparse retrieval",
        "hybrid search",
        "semantic search",
    },
    "devops_cicd": {
        "jenkins",
        "github actions",
        "gitlab ci",
        "circleci",
        "travis ci",
        "argocd",
        "flux",
        "gitops",
        "helm",
        "kustomize",
    },
}

EDUCATION_PATTERNS: dict[str, dict[str, Any]] = {
    "phd": {"keywords": ["phd", "doctorate", "doctor of philosophy"], "score": 1.0},
    "masters": {
        "keywords": ["master", "msc", "m.sc", "m.tech", "m.e", "post graduate", "postgraduate"],
        "score": 0.7,
    },
    "bachelors": {
        "keywords": ["bachelor", "bsc", "b.sc", "b.tech", "b.e", "undergraduate"],
        "score": 0.4,
    },
    "diploma": {
        "keywords": ["diploma", "certificate program", "professional course"],
        "score": 0.2,
    },
}

EDUCATION_FIELDS: dict[str, dict[str, Any]] = {
    "cs": {
        "keywords": [
            "computer science",
            "computer engineering",
            "software engineering",
            "information technology",
            "data science",
            "artificial intelligence",
            "machine learning",
            "computational",
        ],
        "score": 1.0,
    },
    "engineering": {
        "keywords": [
            "engineering",
            "electrical",
            "electronics",
            "mechanical",
            "civil",
            "aerospace",
            "mathematics",
            "physics",
            "statistics",
        ],
        "score": 0.7,
    },
    "business": {
        "keywords": [
            "business administration",
            "mba",
            "finance",
            "economics",
            "commerce",
            "management",
            "marketing",
        ],
        "score": 0.4,
    },
    "sciences": {
        "keywords": [
            "biology",
            "chemistry",
            "biotechnology",
            "life sciences",
            "environmental",
            "neuroscience",
            "cognitive science",
        ],
        "score": 0.3,
    },
}

CERTIFICATION_PATTERNS: list[str] = [
    "aws certified",
    "gcp certified",
    "azure certified",
    "pmp",
    "certified scrum master",
    "csm",
    "cissp",
    "tensorflow certificate",
    "tensorflow developer certificate",
    "databricks certified",
    "snowflake certified",
    "kafka certified",
    "kubernetes certification",
    "cka",
    "ckad",
    "terraform certified",
    "hashicorp certified",
    "comptia",
    "aws solutions architect",
    "aws developer",
    "google professional",
    "oracle certified",
    "red hat certified",
    "cisco certified",
]

NON_TECH_TITLES: list[str] = [
    "marketing",
    "hr",
    "sales",
    "accountant",
    "content",
    "writer",
    "designer",
    "support",
    "executive",
]

PREFERRED_LOCATIONS: dict[str, dict[str, Any]] = {
    "india_tier1": {
        "cities": {
            "bangalore",
            "bengaluru",
            "hyderabad",
            "pune",
            "mumbai",
            "chennai",
            "delhi",
            "gurgaon",
            "gurugram",
            "noida",
        },
        "score": 1.0,
    },
    "india_tier2": {
        "cities": {
            "kolkata",
            "ahmedabad",
            "jaipur",
            "lucknow",
            "chandigarh",
            "indore",
            "bhopal",
            "coimbatore",
            "kochi",
            "nagpur",
        },
        "score": 0.80,
    },
    "global_hub": {
        "cities": {
            "san francisco",
            "new york",
            "london",
            "seattle",
            "berlin",
            "singapore",
            "toronto",
            "zurich",
            "amsterdam",
            "sydney",
        },
        "score": 0.75,
    },
    "global_other": {
        "score": 0.40,
    },
}
